name: lobe-chat-development
services:
  network-service:
    image: alpine
    container_name: lobe-network
    restart: always
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
      - '3000:3000' # Grafana
      - '4318:4318' # otel-collector HTTP
      - '4317:4317' # otel-collector gRPC
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: postgresql
  minio:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: minio
  casdoor:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: casdoor
  searxng:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: searxng

  grafana:
    profiles:
      - otel
    extends:
      file: docker-compose/local/grafana/docker-compose.yml
      service: grafana

  tempo:
    profiles:
      - otel
    extends:
      file: docker-compose/local/grafana/docker-compose.yml
      service: tempo

  prometheus:
    profiles:
      - otel
    extends:
      file: docker-compose/local/grafana/docker-compose.yml
      service: prometheus

  otel-collector:
    profiles:
      - otel
    extends:
      file: docker-compose/local/grafana/docker-compose.yml
      service: otel-collector

  otel-tracing-test:
    profiles:
      - otel-test
    extends:
      file: docker-compose/local/grafana/docker-compose.yml
      service: otel-tracing-test

volumes:
  data:
    driver: local
  s3_data:
    driver: local
  grafana_data:
    driver: local
  tempo_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
