apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
